#!/usr/bin/env python3

# Refactor CSR generated by PeakRDL v1.1.0.
# - Rename some hard-to-read port signal names to remove spelling checker's noisy warnings.
# - Add Verible directives at the beginning of the file to suppress noisy warnings.
# - Convert _pkg.sv file into _pkg.svh file with include guard.

import argparse
import os
import re

def refactor_core_file(file_path: str):
    # Load the file and refactor it.
    with open(file_path, 'r') as file:
        lines = file.readlines()
        # Replace '_axil' with '_axi4lite'
        lines = [line.replace('_axil', '_axi4lite') for line in lines]
        # Replace 'axil_' with 'axi4lite_'
        lines = [line.replace('axil_', 'axi4lite_') for line in lines]
        # Replace '_rptr' with '_rd_ptr'
        lines = [line.replace('_rptr', '_rd_ptr') for line in lines]
        # Replace '_wptr' with '_wr_ptr'
        lines = [line.replace('_wptr', '_wr_ptr') for line in lines]
        # Replace '_biten' with '_bit_en'
        lines = [line.replace('_biten', '_bit_en') for line in lines]
        # Replace 'hwif_out' with 'hw_if_out'
        lines = [line.replace('hwif_out', 'hw_if_out') for line in lines]
        # Replace 'hwif_in' with 'hw_if_in'
        lines = [line.replace('hwif_in', 'hw_if_in') for line in lines]
        # Include _pkg.svh file
        pkg_file_name = os.path.basename(file_path).replace('.sv', '_pkg.svh')
        lines.insert(0, '`include "' + pkg_file_name + '"\n\n')
        # Insert Verible directives
        inserted_str = '''// Verible directive
// verilog_lint: waive-start line-length
// verilog_lint: waive-start typedef-structs-unions

'''
        lines.insert(0, inserted_str)

    # Save the refactored file.
    with open(file_path, 'w') as file:
        file.writelines(lines)

def refactor_pkg_file(file_path_in: str):
    # Load the file and refactor it.
    with open(file_path_in, 'r') as file:
        lines = file.readlines()

        # Replace 'localparam' with 'localparam int'
        pattern = r'(localparam) ([a-zA-Z\d_]+_WIDTH)'
        compiled_pattern = re.compile(pattern)
        for i in range(len(lines)):
            lines[i] = re.sub(compiled_pattern, r'\1 int \2', lines[i])

        # Replace '_biten' with '_bit_en'
        lines = [line.replace('_biten', '_bit_en') for line in lines]
        # Insert Verible directives
        inserted_str = '''// Verible directive
// verilog_lint: waive-start line-length
// verilog_lint: waive-start parameter-name-style
// verilog_lint: waive-start struct-union-name-style

'''
        lines.insert(0, inserted_str)

        # Insert include guard
        pkg_name = os.path.basename(file_path_in).replace('.sv', '')
        inc_guard_begin_txt = '''`ifndef {0}_SVH_INCLUDED\n`define {0}_SVH_INCLUDED\n'''.format(pkg_name.upper())
        inc_guard_end_txt = '\n`endif\n'
        lines.insert(0, inc_guard_begin_txt)
        lines.insert(1, '\n')
        lines.append(inc_guard_end_txt)

    # Save the refactored file as SystemVerilog header file.
    file_path_out = file_path_in.replace('.sv', '.svh')
    with open(file_path_out, 'w') as file:
        file.writelines(lines)

    # Delete the original file
    os.remove(file_path_in)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Refactor SystemVerilog code generated by PeakRDL v1.1.0')
    parser.add_argument('file_path', type=str, help='target core file (not pkg) path')
    args = parser.parse_args()
    refactor_core_file(args.file_path)
    pkg_file_path = args.file_path.replace('.sv', '_pkg.sv')
    refactor_pkg_file(pkg_file_path)
