#!/usr/bin/env python3

# Refactor C header generated by PeakRDL v1.1.0.
# - Replace ifdef-based include guard with `#pragma once`.

import argparse
import os

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Refactor C header generated by PeakRDL v1.1.0.')
    parser.add_argument('file_path', type=str, help='target core file path')
    args = parser.parse_args()

    header_fine_name_without_extension = os.path.basename(args.file_path).replace('.h', '')
    include_guard_macro_name = header_fine_name_without_extension.upper() + '_H'

    with open(args.file_path, 'r') as file:
        lines_in = file.readlines()
        lines_out: list[str] = []
        for i, line in enumerate(lines_in):
            if line.startswith('#ifndef'):
                lines_out.append('#pragma once\n')
            elif line.startswith('#define'):
                # Ignore this line
                pass
            elif line.startswith('#endif /* {0} */'.format(include_guard_macro_name)):
                # Ignore this line
                pass
            else:
                lines_out.append(line)

    # Save the refactored file.
    with open(args.file_path, 'w') as file:
        file.writelines(lines_out)
