// Verible directive
// verilog_lint: waive-start line-length
// verilog_lint: waive-start typedef-structs-unions

`include "my_mod_csr_pkg.svh"

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

extern module my_mod_csr (
        input wire clk,
        input wire rst,

        output logic s_axi4lite_awready,
        input wire s_axi4lite_awvalid,
        input wire [5:0] s_axi4lite_awaddr,
        input wire [2:0] s_axi4lite_awprot,
        output logic s_axi4lite_wready,
        input wire s_axi4lite_wvalid,
        input wire [31:0] s_axi4lite_wdata,
        input wire [3:0]s_axi4lite_wstrb,
        input wire s_axi4lite_bready,
        output logic s_axi4lite_bvalid,
        output logic [1:0] s_axi4lite_bresp,
        output logic s_axi4lite_arready,
        input wire s_axi4lite_arvalid,
        input wire [5:0] s_axi4lite_araddr,
        input wire [2:0] s_axi4lite_arprot,
        input wire s_axi4lite_rready,
        output logic s_axi4lite_rvalid,
        output logic [31:0] s_axi4lite_rdata,
        output logic [1:0] s_axi4lite_rresp,

        input my_mod_csr_pkg::my_mod_csr__in_t hw_if_in,
        output my_mod_csr_pkg::my_mod_csr__out_t hw_if_out
    );
