`ifndef MY_MOD_CSR_PKG_SVH_INCLUDED
`define MY_MOD_CSR_PKG_SVH_INCLUDED

// Verible directive
// verilog_lint: waive-start line-length
// verilog_lint: waive-start parameter-name-style
// verilog_lint: waive-start struct-union-name-style

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package my_mod_csr_pkg;

    localparam int MY_MOD_CSR_DATA_WIDTH = 32;
    localparam int MY_MOD_CSR_MIN_ADDR_WIDTH = 6;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } my_mod_csr__SIMPLE_MEM__in_t;

    typedef struct {
        my_mod_csr__SIMPLE_MEM__in_t SIMPLE_MEM;
    } my_mod_csr__in_t;

    typedef struct {
        logic [31:0] value;
    } my_mod_csr__PROTECTED_REG__FIELD__out_t;

    typedef struct {
        my_mod_csr__PROTECTED_REG__FIELD__out_t FIELD;
    } my_mod_csr__PROTECTED_REG__out_t;

    typedef struct {
        logic [31:0] value;
    } my_mod_csr__UNLOCK_PROTECTED_REG__UNLOCK__out_t;

    typedef struct {
        my_mod_csr__UNLOCK_PROTECTED_REG__UNLOCK__out_t UNLOCK;
    } my_mod_csr__UNLOCK_PROTECTED_REG__out_t;

    typedef struct {
        logic value;
    } my_mod_csr__SINGLE_PULSE__FIELD__out_t;

    typedef struct {
        my_mod_csr__SINGLE_PULSE__FIELD__out_t FIELD;
    } my_mod_csr__SINGLE_PULSE__out_t;

    typedef struct {
        logic [31:0] value;
    } my_mod_csr__WRITE_ONCE__FIELD__out_t;

    typedef struct {
        my_mod_csr__WRITE_ONCE__FIELD__out_t FIELD;
    } my_mod_csr__WRITE_ONCE__out_t;

    typedef struct {
        logic req;
        logic [4:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_bit_en;
    } my_mod_csr__SIMPLE_MEM__out_t;

    typedef struct {
        my_mod_csr__PROTECTED_REG__out_t PROTECTED_REG;
        my_mod_csr__UNLOCK_PROTECTED_REG__out_t UNLOCK_PROTECTED_REG;
        my_mod_csr__SINGLE_PULSE__out_t SINGLE_PULSE;
        my_mod_csr__WRITE_ONCE__out_t WRITE_ONCE;
        my_mod_csr__SIMPLE_MEM__out_t SIMPLE_MEM;
    } my_mod_csr__out_t;
endpackage

`endif
