#!/usr/bin/env python3

# Refactor UVM Register Model generated by PeakRDL v1.1.0.
# - Add Verible directives at the beginning of the file to suppress noisy warnings.
# - Add include guard macro
# - Remove trailing spaces

import argparse
import os

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Refactor SystemVerilog code generated by PeakRDL v1.1.0')
    parser.add_argument('file_path', type=str, help='target core file (not pkg) path')
    args = parser.parse_args()

    file_path = args.file_path
    file_name = os.path.basename(args.file_path)
    pkg_name = file_name.replace('.svh', '')

    with open(file_path, 'r') as file:
        lines = file.readlines()

        # Insert Verible directives
        verible_directives = '''// Verible directive
// verilog_lint: waive-start line-length
'''
        lines.insert(0, verible_directives)

        # Insert include guard
        inc_guard_begin_txt = '''`ifndef {0}_SVH_INCLUDED\n`define {0}_SVH_INCLUDED\n'''.format(pkg_name.upper())
        inc_guard_end_txt = '\n`endif\n'
        lines.insert(0, inc_guard_begin_txt)
        lines.insert(1, '\n')
        lines.append(inc_guard_end_txt)

        # Remove trailing spaces
        lines = [line.rstrip() + '\n' for line in lines]

    # Save the refactored file.
    with open(file_path, 'w') as file:
        file.writelines(lines)
