# TCL File Generated by Component Editor 23.1
# Sun Sep 01 21:44:56 JST 2024
# DO NOT MODIFY


# 
# my_avmm_agt "my_avmm_agt" v0.1.0
# motchy 2024.09.01.21:44:56
# A quite simple Avalon-MM agent template with 4 writable registers. This module doesn't support pipelined transfer, but this is enough in most cases (such as CSR).
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module my_avmm_agt
# 
set_module_property DESCRIPTION "A quite simple Avalon-MM agent template with 4 writable registers. This module doesn't support pipelined transfer, but this is enough in most cases (such as CSR)."
set_module_property NAME my_avmm_agt
set_module_property VERSION 0.1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR motchy
set_module_property ICON_PATH ./
set_module_property DISPLAY_NAME my_avmm_agt
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL my_avmm_agt_v0_1_1
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file my_avmm_agt_v0_1_1.sv SYSTEM_VERILOG PATH ../user_src/rtl/my_avmm_agt_v0_1_1.sv
add_fileset_file avmm_if_defs_pkg_v0_1_0.svh SYSTEM_VERILOG_INCLUDE PATH ../user_src/rtl/avmm_if_defs_pkg_v0_1_0.svh


# 
# parameters
# 
add_parameter AVMM_ADDR_BIT_WIDTH POSITIVE 2 "Bit width of Avalon-MM address bus. The addressing is **word**."
set_parameter_property AVMM_ADDR_BIT_WIDTH DEFAULT_VALUE 2
set_parameter_property AVMM_ADDR_BIT_WIDTH DISPLAY_NAME AVMM_ADDR_BIT_WIDTH
set_parameter_property AVMM_ADDR_BIT_WIDTH WIDTH ""
set_parameter_property AVMM_ADDR_BIT_WIDTH TYPE POSITIVE
set_parameter_property AVMM_ADDR_BIT_WIDTH UNITS None
set_parameter_property AVMM_ADDR_BIT_WIDTH ALLOWED_RANGES 1:2147483647
set_parameter_property AVMM_ADDR_BIT_WIDTH DESCRIPTION "Bit width of Avalon-MM address bus. The addressing is **word**."
set_parameter_property AVMM_ADDR_BIT_WIDTH HDL_PARAMETER true
add_parameter AVMM_DATA_BIT_WIDTH POSITIVE 32 "bit width of Avalon-MM data bus"
set_parameter_property AVMM_DATA_BIT_WIDTH DEFAULT_VALUE 32
set_parameter_property AVMM_DATA_BIT_WIDTH DISPLAY_NAME AVMM_DATA_BIT_WIDTH
set_parameter_property AVMM_DATA_BIT_WIDTH WIDTH ""
set_parameter_property AVMM_DATA_BIT_WIDTH TYPE POSITIVE
set_parameter_property AVMM_DATA_BIT_WIDTH UNITS None
set_parameter_property AVMM_DATA_BIT_WIDTH ALLOWED_RANGES 1:2147483647
set_parameter_property AVMM_DATA_BIT_WIDTH DESCRIPTION "bit width of Avalon-MM data bus"
set_parameter_property AVMM_DATA_BIT_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avmm_agt
# 
add_interface avmm_agt avalon end
set_interface_property avmm_agt addressUnits WORDS
set_interface_property avmm_agt associatedClock clock
set_interface_property avmm_agt associatedReset reset
set_interface_property avmm_agt bitsPerSymbol 8
set_interface_property avmm_agt burstOnBurstBoundariesOnly false
set_interface_property avmm_agt burstcountUnits WORDS
set_interface_property avmm_agt explicitAddressSpan 0
set_interface_property avmm_agt holdTime 0
set_interface_property avmm_agt linewrapBursts false
set_interface_property avmm_agt maximumPendingReadTransactions 0
set_interface_property avmm_agt maximumPendingWriteTransactions 0
set_interface_property avmm_agt readLatency 0
set_interface_property avmm_agt readWaitTime 1
set_interface_property avmm_agt setupTime 0
set_interface_property avmm_agt timingUnits Cycles
set_interface_property avmm_agt writeWaitTime 0
set_interface_property avmm_agt ENABLED true
set_interface_property avmm_agt EXPORT_OF ""
set_interface_property avmm_agt PORT_NAME_MAP ""
set_interface_property avmm_agt CMSIS_SVD_VARIABLES ""
set_interface_property avmm_agt SVD_ADDRESS_GROUP ""

add_interface_port avmm_agt avmm_agt_read read Input 1
add_interface_port avmm_agt avmm_agt_write write Input 1
add_interface_port avmm_agt avmm_agt_address address Input "((AVMM_ADDR_BIT_WIDTH-1)) - (0) + 1"
add_interface_port avmm_agt avmm_agt_writedata writedata Input "((AVMM_DATA_BIT_WIDTH-1)) - (0) + 1"
add_interface_port avmm_agt avmm_agt_byteenable byteenable Input "(((AVMM_DATA_BIT_WIDTH/8)-1)) - (0) + 1"
add_interface_port avmm_agt avmm_agt_readdata readdata Output "((AVMM_DATA_BIT_WIDTH-1)) - (0) + 1"
add_interface_port avmm_agt avmm_agt_response response Output 2
set_interface_assignment avmm_agt embeddedsw.configuration.isFlash 0
set_interface_assignment avmm_agt embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avmm_agt embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avmm_agt embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock i_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset i_sync_rst reset Input 1

